### ISSUE TITLE
Plugin promo issues

### ISSUE THREAD

**Issue by plaidpowered** [Barn2Media/document-library-lite#2]
Two low-priority issues with the current version:

(1) There is a double border around the plugin promo bar, this is fixed simply by updating to the latest barn2-lib. The version in use had an issue with our non-WC plugins.

(2) After updating barn2-lib, the promo bar will never float to the right of the page. This could be an issue with barn2-lib, but adding promo_wrap_start/end fields to the settings page should fix it. Again, this may only be an issue on non-WC plugins and maybe we need to fix it globally.

**Comment by andykeith** [comment]
Thanks Paul, I'll take a look. I did test the new promos with non-WC plugins so it might just be a simple tweak needed somewhere.

**Comment by andykeith** [comment]
@dnusca Could you take a look at this? I think a couple of changes to `Admin/Page/Settings.php` will fix it. 

- In [render_settings_page](https://github.com/Barn2Media/document-library-lite/blob/3c1bb2cd845fa20b7748212b8bdbb4f6f166c65a/src/Admin/Page/Settings.php#L102), I think you can remove the `barn2-plugins-settings` class and `barn2-settings-inner` (and maybe the whole `dlw-settings` div?)
- Pass `$this->plugin->get_id()` to `do_action( 'barn2_before_plugin_settings' );`

More info on Slack [here](https://barn2.slack.com/archives/CPVA3K2MC/p1652447467720929).

**Comment by dnusca** [comment]
Thanks all.

This has been released in 1.0.2
